 SUBROUTINE ALLOCATE_VARIABLE() 
 USE ALL_VAR
 USE CONTROL, ONLY : ISLON,IELON,ISLAT,IELAT,IPART
 USE CONST, ONLY : LE
 USE LIMS, ONLY : IM,JM,KB
 IMPLICIT NONE
 INTEGER IERR
 INTEGER I1,I2,J1,J2
 
 I1=ISLON-LE
 I2=IELON+LE
 J1=ISLAT-LE
 J2=IELAT+LE
!! LOCATE MEMORY FOR THE VARIABLES THAT SETTED 
!! AND NEVER RESET
 ALLOCATE(X(IM),STAT=IERR) 
 CALL ISLOCATE(IERR)
 ALLOCATE(Y(JM),STAT=IERR) 
 CALL ISLOCATE(IERR)
 ALLOCATE(Z(KB),ZZ(KB),DZ(KB),DZZ(KB),STAT=IERR) 
 CALL ISLOCATE(IERR)




 ALLOCATE(FSM(I1:I2,J1:J2),STAT=IERR) 
 CALL ISLOCATE(IERR)
 ALLOCATE(H(I1:I2,J1:J2),STAT=IERR) 
 CALL ISLOCATE(IERR)
 ALLOCATE(DX(I1:I2,J1:J2),STAT=IERR) 
 CALL ISLOCATE(IERR)
 ALLOCATE(DY(I1:I2,J1:J2),STAT=IERR) 
 CALL ISLOCATE(IERR)
 ALLOCATE(ART(I1:I2,J1:J2),STAT=IERR) 
 CALL ISLOCATE(IERR)
 ALLOCATE(COR(I1:I2,J1:J2),STAT=IERR) 
 CALL ISLOCATE(IERR)
 ALLOCATE(ARU(I1:I2,J1:J2),STAT=IERR) 
 CALL ISLOCATE(IERR)
 ALLOCATE(ARV(I1:I2,J1:J2),STAT=IERR) 
 CALL ISLOCATE(IERR)
 ALLOCATE(DUM(I1:I2,J1:J2),STAT=IERR) 
 CALL ISLOCATE(IERR)
 ALLOCATE(DVM(I1:I2,J1:J2),STAT=IERR) 
 CALL ISLOCATE(IERR)
!!    LOCATE MEMORY FOR 2 DIMENSION VARIABLES
 ALLOCATE(UTB(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(VTB(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(UTF(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(VTF(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(ADVUA(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(ADVVA(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(TSURF(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(SSURF(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(DRX2D(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(DRY2D(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(ADX2D(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(ADY2D(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(SWRAD(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
!!C   define variable
 ALLOCATE(D(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(DT(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
!!C  2     
 ALLOCATE(CBC(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
!!C  5   
 ALLOCATE(WUSURF(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(WVSURF(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(WUBOT(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(WVBOT(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
!!C  6    
 ALLOCATE(WTSURF(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(WSSURF(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(TPS(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(AAM2D(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
!!C  7     
 ALLOCATE(UAF(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(UA(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(UAB(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)

 ALLOCATE(VAF(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(VA(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(VAB(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
!!C  8    
 ALLOCATE(ELF(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(EL(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(ELB(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(PSI(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)


!!C  9
 ALLOCATE(ETF(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(ET(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(ETB(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(FLUXUA(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(FLUXVA(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
!!C  10    
 ALLOCATE(EGF(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(EGB(I1:I2,J1:J2),STAT=IERR)
 CALL ISLOCATE(IERR)
!!   LOCATE MEMORY FOR 3 DIMENSION VARIABLES
 ALLOCATE(ADVX(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR)      
 ALLOCATE(ADVY(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR)      
 ALLOCATE(DRHOX(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR)      
 ALLOCATE(DRHOY(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR)      
 ALLOCATE(TCLIM(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR)      
 ALLOCATE(SCLIM(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
!!C   define variable in comblk98.h
!!   1 
 ALLOCATE(A(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(C(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(EE(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(GG(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
!!   2 
 ALLOCATE(UF(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(VF(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(ZDE(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
!!   3
 ALLOCATE(KM(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(KH(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(KQ(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(L(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
!!   4
 ALLOCATE(Q2(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(Q2B(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(AAM(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
!!   5
 ALLOCATE(Q2L(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(Q2LB(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(WZ(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
!!   6
 ALLOCATE(U(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(UB(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(W(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(W2(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
!!   7
 ALLOCATE(V(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(VB(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
!!   8
 ALLOCATE(T(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(TB(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
!!   9
 ALLOCATE(S(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(SB(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
!!   10
 ALLOCATE(RHO(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(DTEF(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
 ALLOCATE(RMEAN(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 

 ALLOCATE(BV(I1:I2,J1:J2,KB),STAT=IERR)
 CALL ISLOCATE(IERR) 
!!    1 AND 2-D BOUNDARY VALUE ARRAYS
 ALLOCATE(TBN(ISLON:IELON,KB),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(TBS(ISLON:IELON,KB),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(SBN(ISLON:IELON,KB),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(SBS(ISLON:IELON,KB),STAT=IERR)
 CALL ISLOCATE(IERR)

 ALLOCATE(UBN(ISLON:IELON,KB),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(UBS(ISLON:IELON,KB),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(VBN(ISLON:IELON,KB),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(VBS(ISLON:IELON,KB),STAT=IERR)
 CALL ISLOCATE(IERR)

 ALLOCATE(ELN(ISLON:IELON),STAT=IERR)
 CALL ISLOCATE(IERR)  
 ALLOCATE(ELS(ISLON:IELON),STAT=IERR)
 CALL ISLOCATE(IERR)  
 ALLOCATE(VABN(ISLON:IELON),STAT=IERR)
 CALL ISLOCATE(IERR)  
 ALLOCATE(VABS(ISLON:IELON),STAT=IERR)
 CALL ISLOCATE(IERR) 

 ALLOCATE(TBE(ISLAT:IELAT,KB),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(TBW(ISLAT:IELAT,KB),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(SBE(ISLAT:IELAT,KB),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(SBW(ISLAT:IELAT,KB),STAT=IERR)
 CALL ISLOCATE(IERR)

 ALLOCATE(UBE(ISLAT:IELAT,KB),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(UBW(ISLAT:IELAT,KB),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(VBE(ISLAT:IELAT,KB),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(VBW(ISLAT:IELAT,KB),STAT=IERR)
 CALL ISLOCATE(IERR)

 ALLOCATE(UABW(ISLAT:IELAT),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(UABE(ISLAT:IELAT),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(ELE(ISLAT:IELAT),STAT=IERR)
 CALL ISLOCATE(IERR)
 ALLOCATE(ELW(ISLAT:IELAT),STAT=IERR)
 CALL ISLOCATE(IERR)


 X = 0.
 Y = 0.
 Z = 0.
 ZZ = 0.
 DZ = 0.
 DZZ = 0.
 FSM(I1:I2,J1:J2) = 0.
 H(I1:I2,J1:J2) = 0.
 DX(I1:I2,J1:J2) = 0.
 DY(I1:I2,J1:J2) = 0.
 ART(I1:I2,J1:J2) = 0.
 COR(I1:I2,J1:J2) = 0.
 ARU(I1:I2,J1:J2) = 0.
 ARV(I1:I2,J1:J2) = 0.
 DUM(I1:I2,J1:J2) = 0.
 DVM(I1:I2,J1:J2) = 0.
 UTB(I1:I2,J1:J2) = 0.
 VTB(I1:I2,J1:J2) = 0.
 UTF(I1:I2,J1:J2) = 0.
 VTF(I1:I2,J1:J2) = 0.
 ADVUA(I1:I2,J1:J2) = 0.
 ADVVA(I1:I2,J1:J2) = 0.
 TSURF(I1:I2,J1:J2) = 0.
 SSURF(I1:I2,J1:J2) = 0.
 DRX2D(I1:I2,J1:J2) = 0.
 DRY2D(I1:I2,J1:J2) = 0.
 ADX2D(I1:I2,J1:J2) = 0.
 ADY2D(I1:I2,J1:J2) = 0.
 SWRAD(I1:I2,J1:J2) = 0.
 D(I1:I2,J1:J2) = 0.
 DT(I1:I2,J1:J2) = 0.
 CBC(I1:I2,J1:J2) = 0.
 WUSURF(I1:I2,J1:J2) = 0.
 WVSURF(I1:I2,J1:J2) = 0.
 WUBOT(I1:I2,J1:J2) = 0.
 WVBOT(I1:I2,J1:J2) = 0.
 WTSURF(I1:I2,J1:J2) = 0.
 WSSURF(I1:I2,J1:J2) = 0.
 TPS(I1:I2,J1:J2) = 0.
 AAM2D(I1:I2,J1:J2) = 0.
 UAF(I1:I2,J1:J2) = 0.
 UA(I1:I2,J1:J2) = 0.
 UAB(I1:I2,J1:J2) = 0.
 VAF(I1:I2,J1:J2) = 0.
 VA(I1:I2,J1:J2) = 0.
 VAB(I1:I2,J1:J2) = 0.
 ELF(I1:I2,J1:J2) = 0.
 EL(I1:I2,J1:J2) = 0.
 ELB(I1:I2,J1:J2) = 0.
 PSI(I1:I2,J1:J2) = 0.
 ETF(I1:I2,J1:J2) = 0.
 ET(I1:I2,J1:J2) = 0.
 ETB(I1:I2,J1:J2) = 0.
 FLUXUA(I1:I2,J1:J2) = 0.
 FLUXVA(I1:I2,J1:J2) = 0.
 EGF(I1:I2,J1:J2) = 0.
 EGB(I1:I2,J1:J2) = 0.
 ADVX(I1:I2,J1:J2,:) = 0.
 ADVY(I1:I2,J1:J2,:) = 0.
 DRHOX(I1:I2,J1:J2,:) = 0.
 DRHOY(I1:I2,J1:J2,:) = 0.
 TCLIM(I1:I2,J1:J2,:) = 0.
 SCLIM(I1:I2,J1:J2,:) = 0.
 A(I1:I2,J1:J2,:) = 0.
 C(I1:I2,J1:J2,:) = 0.
 EE(I1:I2,J1:J2,:) = 0.
 GG(I1:I2,J1:J2,:) = 0.
 UF(I1:I2,J1:J2,:) = 0.
 VF(I1:I2,J1:J2,:) = 0.
 ZDE(I1:I2,J1:J2,:) = 0.
 KM(I1:I2,J1:J2,:) = 0.
 KH(I1:I2,J1:J2,:) = 0.
 KQ(I1:I2,J1:J2,:) = 0.
 L(I1:I2,J1:J2,:) = 0.
 Q2(I1:I2,J1:J2,:) = 0.
 Q2B(I1:I2,J1:J2,:) = 0.
 AAM(I1:I2,J1:J2,:) = 0.
 Q2L(I1:I2,J1:J2,:) = 0.
 Q2LB(I1:I2,J1:J2,:) = 0.
 WZ(I1:I2,J1:J2,:) = 0.
 U(I1:I2,J1:J2,:) = 0.
 UB(I1:I2,J1:J2,:) = 0.
 W(I1:I2,J1:J2,:) = 0.
 W2(I1:I2,J1:J2,:) = 0.
 V(I1:I2,J1:J2,:) = 0.
 VB(I1:I2,J1:J2,:) = 0.
 T(I1:I2,J1:J2,:) = 0.
 TB(I1:I2,J1:J2,:) = 0.
 S(I1:I2,J1:J2,:) = 0.
 SB(I1:I2,J1:J2,:) = 0.
 RHO(I1:I2,J1:J2,:) = 0.
 DTEF(I1:I2,J1:J2,:) = 0.
 RMEAN(I1:I2,J1:J2,:) = 0.
 BV(I1:I2,J1:J2,:) = 0.
 TBN(ISLON:IELON,:) = 0.
 TBS(ISLON:IELON,:) = 0.
 SBN(ISLON:IELON,:) = 0.
 SBS(ISLON:IELON,:) = 0.
 ELN(ISLON:IELON) = 0.
 ELS(ISLON:IELON) = 0.
 VABN(ISLON:IELON) = 0.
 VABS(ISLON:IELON) = 0.
 TBE(ISLAT:IELAT,:) = 0.
 TBW(ISLAT:IELAT,:) = 0.
 SBE(ISLAT:IELAT,:) = 0.
 SBW(ISLAT:IELAT,:) = 0.
 UABW(ISLAT:IELAT) = 0.
 UABE(ISLAT:IELAT) = 0.
 ELE(ISLAT:IELAT) = 0.
 ELW(ISLAT:IELAT) = 0.
 UBS(ISLON:IELON,:) = 0.
 UBN(ISLON:IELON,:) = 0.
 UBW(ISLAT:IELAT,:) = 0.
 UBE(ISLAT:IELAT,:) = 0.
 VBS(ISLON:IELON,:) = 0.
 VBN(ISLON:IELON,:) = 0.
 VBW(ISLAT:IELAT,:) = 0.
 VBE(ISLAT:IELAT,:) = 0.



 IPART=0



 RETURN 
 END
!!**********************************************************
 SUBROUTINE ISLOCATE(IERR)
 IMPLICIT NONE
 INTEGER IERR
 IF(IERR>0)THEN
   print*,"Allocation error!"
   stop
 END IF
 END  
