SUBROUTINE CFL
USE CONST
USE CONTROL
USE ALL_VAR, ONLY : DX,DY,FSM,H,TPS
IMPLICIT NONE
!  Evaluate external CFL time step
DO J=ISLAT,IELAT
DO I=ISLON,IELON
TPS(I,J)=0.5E0/SQRT(1.E0/DX(I,J)**2+1.E0/DY(I,J)**2)  &
         /SQRT(GRAV*H(I,J))*FSM(I,J)
END DO
END DO
RETURN
END
