 SUBROUTINE DEALLOCATE_VARIABLE() 
 USE ALL_VAR
 USE CONTROL
 USE coupling_pom_mod      !zhaobiao, c-coupler2
 IMPLICIT NONE
 
!! LOCATE MEMORY FOR THE VARIABLES THAT SETTED 
!! AND NEVER RESET
 DEALLOCATE(X,Y,Z,ZZ,DZ,DZZ)
 DEALLOCATE(FSM,H,DX,DY,ART,COR,ARU,ARV,DUM,DVM)
!!    LOCATE MEMORY FOR 2 DIMENSION VARIABLES
 DEALLOCATE(UTB,VTB,UTF,VTF,ADVUA,ADVVA,TSURF,SSURF, &
            DRX2D,DRY2D,ADX2D,ADY2D,SWRAD)
!!C   define variable
 DEALLOCATE(D,DT)
!!C  2     
 DEALLOCATE(CBC)
!!C  5   
 DEALLOCATE(WUSURF,WVSURF,WUBOT,WVBOT)
!!C  6    
 DEALLOCATE(WTSURF,WSSURF,TPS,AAM2D)
!!C  7     
 DEALLOCATE(UAF,UA,UAB,VAF,VA,VAB)
!!C  8    
 DEALLOCATE(ELF,EL,ELB,PSI)
!!C  9
 DEALLOCATE(ETF,ET,ETB,FLUXUA,FLUXVA)
!!C  10    
 DEALLOCATE(EGF,EGB)
!!   LOCATE MEMORY FOR 3 DIMENSION VARIABLES
 DEALLOCATE(ADVX,ADVY,DRHOX,DRHOY,TCLIM,SCLIM)
!!C   define variable in comblk98.h
!!   1 
 DEALLOCATE(A,C,EE,GG)
!!   2 
 DEALLOCATE(UF,VF,ZDE)
!!   3
 DEALLOCATE(KM,KH,KQ,L)
!!   4
 DEALLOCATE(Q2,Q2B,AAM)
!!   5
 DEALLOCATE(Q2L,Q2LB,WZ)
!!   6
 DEALLOCATE(U,UB,W,W2)
!!   7
 DEALLOCATE(V,VB)
!!   8
 DEALLOCATE(T,TB)
!!   9
 DEALLOCATE(S,SB)
!!   10
 DEALLOCATE(RHO,DTEF,RMEAN,BV)
!!    1 AND 2-D BOUNDARY VALUE ARRAYS
 DEALLOCATE(TBN,TBS,SBN,SBS)

 DEALLOCATE(ELN,ELS,VABN,VABS)

 DEALLOCATE(TBE,TBW,SBE,SBW)

 DEALLOCATE(ELE,ELW,UABW,UABE)
 
 IF(TIDETYPE)THEN
 DEALLOCATE(AMPE,AMPW,PHAE,PHAW,AMPS,AMPN,PHAS,PHAN,M2UVE,M2UVW,M2UVS,M2UVN,OMG)
 END IF

 DEALLOCATE(IPART)
 CALL release_pom_buf      !zhaobiao, c-coupler2
 
 RETURN 
 END
