 SUBROUTINE DEPTH
 USE data_kind_mod
 USE CONTROL
 USE LIMS, ONLY : KB
 USE ALL_VAR, ONLY : Z,DZ,ZZ,DZZ,ZSS
 IMPLICIT NONE
! ***
! THIS SUBROUTINE ESTABLISHES THE VERTICAL SIGMA GRID WITH LOG
! DISTRIBUTIONS  AT THE TOP AND BOTTOM AND A LINEAR DISTRIBUTION
! BETWEEN. CHOOSE KL1 AND KL2. THE VALUES, KL1 = 2 AND KL2 = KB-2,
! YIELD AN EQUALLY SPACED DISTRIBUTION WITH NO LOG PORTIONS.   
! 	
  
 DO K=1,KB
 Z(K)=-ZSS(K)/ZSS(KB)
 ENDDO

 DO K=1,KB-1
 ZZ(K)=0.5*(Z(K)+Z(K+1))
 END DO
   
 ZZ(KB)=2.*ZZ(KB-1)-ZZ(KB-2)
 
 DO K=1,KB-1
 DZ(K)=Z(K)-Z(K+1)
 DZZ(K)=ZZ(K)-ZZ(K+1)
 END DO

 DZ(KB)=0.
 DZZ(KB)=0.

 IF(MSR)THEN
 OPEN(123,FILE='depth.dat')
 WRITE(123,70)
 DO K=1,KB
 WRITE(123,80)K,Z(K),ZZ(K),DZ(K),DZZ(K)
 END DO
70 FORMAT(/2X,'K',7X,'Z',9X,'ZZ',9X,'DZ',9X,'DZZ',/)
80 FORMAT(' ',I5,4F10.5)
 CLOSE(123)
 END IF
 RETURN
 END
