 SUBROUTINE INITIAL
 USE ALL_VAR, ONLY : TB,SB,RHO,RMEAN,DT,H,FSM,DZ,      &
     UAB,VAB,ETB,ELB,AAM2D,ZZ,DUM,Q2B,Q2LB,KH,KM,L,KQ, &
     AAM,UA,VA,EL,ET,ETB,ELB,ETF,D,DRX2D,DRY2D,Q2,Q2L, &
     T,S,U,V,TCLIM,SCLIM,UB,VB,TSURF,SSURF,L,DRHOX,    &
     DRHOY,RFE,RFW,RFN,RFS,DUM,DVM
 USE NcFileMod
 USE CONST, ONLY : LAND,TBIAS,SBIAS,SMALL,VEL
 USE LIMS
 USE CONTROL
 USE PARALLEL_MOD
 IMPLICIT NONE
!>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
! SET PARAMETER FOR BOUNDARY
 RFN=0;RFS=0;RFE=0;RFW=0
 IF(IELON==IM)RFE=1
 IF(ISLON==1)RFW=1
 IF(IELAT==JM)RFN=1
 IF(ISLAT==1)RFS=1
!>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
! output TB SB RMEAN
 CALL INITIAL_TS 
!>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
 DO K=1,KBM1
 DO J=ISLAT,IELAT
 DO I=ISLON,IELON
    TCLIM(I,J,K)=TB(I,J,K)
    SCLIM(I,J,K)=SB(I,J,K)
    UB(I,J,K)=VEL*DUM(I,J)
    VB(I,J,K)=0.
    AAM(I,J,K)=500.
 END DO
 END DO
 END DO

 CALL COMM_3D(TCLIM,2,2)
 CALL COMM_3D(SCLIM,2,2)
 CALL COMM_3D(UB,2,2)
 CALL COMM_3D(VB,2,2)
 CALL COMM_3D(AAM,2,2)

 DO J=ISLAT,IELAT
 DO I=ISLON,IELON
    TSURF(I,J)=TCLIM(I,J,1)
    SSURF(I,J)=SCLIM(I,J,1)
 END DO
 END DO
 
 CALL COMM_2D(TSURF,3,3)
 CALL COMM_2D(SSURF,3,3)

 DO J=ISLAT,IELAT
 DO I=ISLON,IELON
    UAB(I,J)=VEL*DUM(I,J)
    VAB(I,J)=0.0
    ELB(I,J)=0.0           
    ETB(I,J)=0.0           
    AAM2D(I,J)=500.
 END DO
 END DO
 CALL COMM_2D(UAB,3,3)
 CALL COMM_2D(VAB,3,3)
 CALL COMM_2D(ELB,3,3)
 CALL COMM_2D(ETB,3,3)
 CALL COMM_2D(AAM2D,3,3)
!>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
!  Additional initial conditions
 DO K=1,KB
 DO J=ISLAT,IELAT
 DO I=ISLON,IELON
 Q2B(I,J,K)=1.E-8
 Q2LB(I,J,K)=1.E-8
 KH(I,J,K)=2.E-4
 KM(I,J,K)=KH(I,J,K)
 L(I,J,K)=Q2LB(I,J,K)/(Q2B(I,J,K)+SMALL)
 KQ(I,J,K)=0.2E0*L(I,J,K)*SQRT(Q2B(I,J,K))
 AAM(I,J,K)=500.
 END DO
 END DO
 END DO
 CALL COMM_3D(Q2B,2,2)
 CALL COMM_3D(Q2LB,2,2)
 CALL COMM_3D(KH,2,2)
 CALL COMM_3D(KM,2,2)
 CALL COMM_3D(L,2,2)
 CALL COMM_3D(KQ,2,2)
 CALL COMM_3D(AAM,2,2)
! 62 Cycle
 DO I=ISLON,IELON
 DO J=ISLAT,IELAT
 UA(I,J)=UAB(I,J)
 VA(I,J)=VAB(I,J)
 EL(I,J)=ELB(I,J)
 ET(I,J)=ETB(I,J)
 ETF(I,J)=ET(I,J)
 D(I,J)=H(I,J)+EL(I,J)
 DT(I,J)=H(I,J)+ET(I,J)
 DRX2D(I,J)=0.
 DRY2D(I,J)=0.
 END DO
 END DO
 CALL COMM_2D(UA,3,3)
 CALL COMM_2D(VA,3,3)
 CALL COMM_2D(EL,3,3)
 CALL COMM_2D(ET,3,3)
 CALL COMM_2D(ETF,3,3)
 CALL COMM_2D(D,3,3)
 CALL COMM_2D(DT,3,3)
! 63 Cycle
 DO K=1,KBM1
 DO I=ISLON,IELON
 DO J=ISLAT,IELAT
 Q2(I,J,K)=Q2B(I,J,K)
 Q2L(I,J,K)=Q2LB(I,J,K)
 T(I,J,K)=TB(I,J,K)
 S(I,J,K)=SB(I,J,K)
 U(I,J,K)=UB(I,J,K)
 V(I,J,K)=VB(I,J,K)
 END DO
 END DO
 END DO
 CALL COMM_3D(T,2,2)
 CALL COMM_3D(S,2,2)
 CALL COMM_3D(U,2,2)
 CALL COMM_3D(V,2,2)
 CALL COMM_3D(Q2,2,2)
 CALL COMM_3D(Q2L,2,2)

 CALL DENS(S,T,RHO,DT)

 CALL COMM_3D(RHO,2,2)
 FACT=1.
 CALL BAROPG
 DO K=1,KBM1
 DO J=ISLAT,IELAT
 DO I=ISLON,IELON
 DRX2D(I,J)=DRX2D(I,J)+DRHOX(I,J,K)*DZ(K)
 DRY2D(I,J)=DRY2D(I,J)+DRHOY(I,J,K)*DZ(K)
 END DO
 END DO
 END DO
 !CALL COMM_2D(DRX2D,3,3)
 !CALL COMM_2D(DRY2D,3,3)
!>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 RETURN
 END
