 SUBROUTINE INITIAL_BC 
 USE CONTROL
 USE LIMS
 USE MOD_IO
 USE ALL_VAR,ONLY: SSOUTH,TSOUTH,SNORTH,TNORTH,       &
                   SEAST,TEAST,SWEST,TWEST,           &
                   USOUTH,VSOUTH,UNORTH,VNORTH,       &
                   UEAST,VEAST,UWEST,VWEST,           &
                   ETSOUTH,VASOUTH,ETNORTH,VANORTH,   &
                   ETEAST,UAEAST,ETWEST,UAWEST,FSM,   &
                   RFE,RFW,RFS,RFN

 IMPLICIT NONE
 INTEGER,PARAMETER:: JJTIME=2
 

!>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
! SET BCTYPE
! for south
 IF(RFS)THEN
 ALLOCATE(SSOUTH(ISLON:IELON,KB,JJTIME),TSOUTH(ISLON:IELON,KB,JJTIME))
 ALLOCATE(USOUTH(ISLON:IELON,KB,JJTIME),VSOUTH(ISLON:IELON,KB,JJTIME))
 ALLOCATE(ETSOUTH(ISLON:IELON,JJTIME),VASOUTH(ISLON:IELON,JJTIME))
 END IF
! for north 
 IF(RFN)THEN
 ALLOCATE(SNORTH(ISLON:IELON,KB,JJTIME),TNORTH(ISLON:IELON,KB,JJTIME))
 ALLOCATE(UNORTH(ISLON:IELON,KB,JJTIME),VNORTH(ISLON:IELON,KB,JJTIME))
 ALLOCATE(ETNORTH(ISLON:IELON,JJTIME),VANORTH(ISLON:IELON,JJTIME))
 END IF
! for west
 IF(RFW)THEN
 ALLOCATE(SWEST(ISLAT:IELAT,KB,JJTIME),TWEST(ISLAT:IELAT,KB,JJTIME))
 ALLOCATE(UWEST(ISLAT:IELAT,KB,JJTIME),VWEST(ISLAT:IELAT,KB,JJTIME))
 ALLOCATE(ETWEST(ISLAT:IELAT,JJTIME),UAWEST(ISLAT:IELAT,JJTIME))
 END IF
! for east
 IF(RFE)THEN
 ALLOCATE(SEAST(ISLAT:IELAT,KB,JJTIME),TEAST(ISLAT:IELAT,KB,JJTIME))
 ALLOCATE(UEAST(ISLAT:IELAT,KB,JJTIME),VEAST(ISLAT:IELAT,KB,JJTIME))
 ALLOCATE(ETEAST(ISLAT:IELAT,JJTIME),UAEAST(ISLAT:IELAT,JJTIME))
 END IF
!>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 CALL READ_BC(T1) 
 RETURN
 END
