 SUBROUTINE READ_BC(TTT) 
 USE NcFileMod
 USE CONST, ONLY : LAND
 USE CONTROL
 USE LIMS
 USE time_mod
 USE ALL_VAR, ONLY : SSOUTH,TSOUTH,SNORTH,TNORTH,       &
                     SEAST,TEAST,SWEST,TWEST,           &
                     USOUTH,VSOUTH,UEAST,VEAST,UWEST,   &
                     VWEST,UNORTH,VNORTH,               &
                     ETSOUTH,VASOUTH,ETNORTH,VANORTH,   &
                     ETEAST,UAEAST,ETWEST,UAWEST,FSM,   &
                     DUM,DVM,RFE,RFS,RFN,RFW
 IMPLICIT NONE
 CHARACTER*200 FileName,FileName1
 INTEGER,PARAMETER :: JJTIME=2
 REAL(kind_r4),DIMENSION(IM,KB) :: TMPIM
 REAL(kind_r4),DIMENSION(JM,KB) :: TMPJM
 REAL(kind_r4),DIMENSION(IM) :: TMP2DIM
 REAL(kind_r4),DIMENSION(JM) :: TMP2DJM
 DOUBLE PRECISION TTT,TTT1
 INTEGER L1,L2
 CHARACTER*5 YYYYx,YYYYXX
 INTEGER TTVEC(6)
 
 TTVEC=DATEVEC(TTT,1)
 TTT1=datenum([TTVEC(1),1,1,0,0,0],1)
 L1=INT(TTT-TTT1+1)
 WRITE(YYYYX,'(i4.4,a1)'),TTVEC(1),'_'

 TTVEC=DATEVEC(TTT+1.,1)
 TTT1=datenum([TTVEC(1),1,1,0,0,0],1)
 L2=INT(TTT-TTT1+2)
 WRITE(YYYYXX,'(i4.4,a1)'),TTVEC(1),'_'


!>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
! SET SOUTH BOUNDARY
 IF(RFS)THEN


 FileName=trim(input)//'bc/'//trim(YYYYX)//'bc_s.nc'
 FileName1=trim(input)//'bc/'//trim(YYYYXX)//'bc_s.nc'
 WRITE(6,*)MYID," READ SOUTH BOUDARY DATA ",L1,L2
 WRITE(6,*)MYID,TRIM(FileName)
 WRITE(6,*)MYID,TRIM(FileName1)
! Boundary data for salinity
 CALL Nc_READ(FileName,'SALT',TMPIM,LAND=LAND,I1=1,J1=1,LREC=L1) 
 SSOUTH(ISLON:IELON,:,1)=TMPIM(ISLON:IELON,:)
 CALL Nc_READ(FileName1,'SALT',TMPIM,LAND=LAND,I1=1,J1=1,LREC=L2) 
 SSOUTH(ISLON:IELON,:,2)=TMPIM(ISLON:IELON,:)
! Boundary data for temperature 
 CALL Nc_READ(FileName,'TEMP',TMPIM,LAND=LAND,I1=1,J1=1,LREC=L1) 
 TSOUTH(ISLON:IELON,:,1)=TMPIM(ISLON:IELON,:)
 CALL Nc_READ(FileName1,'TEMP',TMPIM,LAND=LAND,I1=1,J1=1,LREC=L2) 
 TSOUTH(ISLON:IELON,:,2)=TMPIM(ISLON:IELON,:)
! Boundary data for curu 
 CALL Nc_READ(FileName,'CURU',TMPIM,LAND=LAND,I1=1,J1=1,LREC=L1) 
 USOUTH(ISLON:IELON,:,1)=TMPIM(ISLON:IELON,:)
 CALL Nc_READ(FileName1,'CURU',TMPIM,LAND=LAND,I1=1,J1=1,LREC=L2) 
 USOUTH(ISLON:IELON,:,2)=TMPIM(ISLON:IELON,:)
! Boundary data for curu 
 CALL Nc_READ(FileName,'CURV',TMPIM,LAND=LAND,I1=1,J1=1,LREC=L1) 
 VSOUTH(ISLON:IELON,:,1)=TMPIM(ISLON:IELON,:)
 CALL Nc_READ(FileName1,'CURV',TMPIM,LAND=LAND,I1=1,J1=1,LREC=L2) 
 VSOUTH(ISLON:IELON,:,2)=TMPIM(ISLON:IELON,:)
!Boundary data for SEA LEVEL 
 CALL Nc_READ(FileName,'EL',TMP2DIM,LAND=LAND,LREC=L1) 
 ETSOUTH(ISLON:IELON,1)=TMP2DIM(ISLON:IELON)
 CALL Nc_READ(FileName1,'EL',TMP2DIM,LAND=LAND,LREC=L2) 
 ETSOUTH(ISLON:IELON,2)=TMP2DIM(ISLON:IELON)
! Boundary data for average V current
 CALL Nc_READ(FileName,'VA',TMP2DIM,LAND=LAND,LREC=L1) 
 VASOUTH(ISLON:IELON,1)=TMP2DIM(ISLON:IELON)
 CALL Nc_READ(FileName1,'VA',TMP2DIM,LAND=LAND,LREC=L2) 
 VASOUTH(ISLON:IELON,2)=TMP2DIM(ISLON:IELON)
! 
 DO I=ISLON,IELON
 IF(FSM(I,ISLAT)==1)THEN
   DO K=1,JJTIME
    IF(ETSOUTH(I,K)>5.OR.VASOUTH(I,K)>5)THEN
     WRITE(6,*) I,K,"ET_S=",ETSOUTH(I,K)
     STOP
     END IF
   DO J=1,KB
    IF(SSOUTH(I,J,K)>45.OR.TSOUTH(I,J,K)>45)THEN
     WRITE(6,*) I,J,K,"SAL_S=",SSOUTH(I,J,K),"TEMP_S=",TSOUTH(I,J,K)
     STOP
    END IF
   END DO
   END DO
 ELSE
  SSOUTH(I,:,:)=0
  TSOUTH(I,:,:)=0
  ETSOUTH(I,:)=0
 END IF
 
 IF(DVM(I,ISLAT)==1)THEN
  DO K=1,JJTIME
  IF(VASOUTH(I,K)>5)THEN
   WRITE(6,*)"VA_S=",VASOUTH(I,K)
   STOP
  END IF
  END DO
 ELSE
  VASOUTH(I,:)=0
 END IF
 
 END DO

 END IF

!>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
! SET NORTH BOUNDARY
 IF(RFN)THEN


 WRITE(6,*)MYID," READ NORTH BOUDARY DATA ",L1,L2
 FileName=trim(input)//'bc/'//trim(YYYYX)//'bc_n.nc'
 FileName1=trim(input)//'bc/'//trim(YYYYXX)//'bc_n.nc'
 WRITE(6,*)MYID,TRIM(FileName)
 WRITE(6,*)MYID,TRIM(FileName1)
! Boundary data for salinity
 CALL Nc_READ(FileName,'SALT',TMPIM,LAND=LAND,I1=1,J1=1,LREC=L1) 
 SNORTH(ISLON:IELON,:,1)=TMPIM(ISLON:IELON,:)
 CALL Nc_READ(FileName1,'SALT',TMPIM,LAND=LAND,I1=1,J1=1,LREC=L2) 
 SNORTH(ISLON:IELON,:,2)=TMPIM(ISLON:IELON,:)
! Boundary data for temperature 
 CALL Nc_READ(FileName,'TEMP',TMPIM,LAND=LAND,I1=1,J1=1,LREC=L1) 
 TNORTH(ISLON:IELON,:,1)=TMPIM(ISLON:IELON,:)
 CALL Nc_READ(FileName1,'TEMP',TMPIM,LAND=LAND,I1=1,J1=1,LREC=L2) 
 TNORTH(ISLON:IELON,:,2)=TMPIM(ISLON:IELON,:)
! Boundary data for curu 
 CALL Nc_READ(FileName,'CURU',TMPIM,LAND=LAND,I1=1,J1=1,LREC=L1) 
 UNORTH(ISLON:IELON,:,1)=TMPIM(ISLON:IELON,:)
 CALL Nc_READ(FileName1,'CURU',TMPIM,LAND=LAND,I1=1,J1=1,LREC=L2) 
 UNORTH(ISLON:IELON,:,2)=TMPIM(ISLON:IELON,:)
! Boundary data for curv 
 CALL Nc_READ(FileName,'CURV',TMPIM,LAND=LAND,I1=1,J1=1,LREC=L1) 
 VNORTH(ISLON:IELON,:,1)=TMPIM(ISLON:IELON,:)
 CALL Nc_READ(FileName1,'CURV',TMPIM,LAND=LAND,I1=1,J1=1,LREC=L2) 
 VNORTH(ISLON:IELON,:,2)=TMPIM(ISLON:IELON,:)

!Boundary data for SEA LEVEL 
 CALL Nc_READ(FileName,'EL',TMP2DIM,LAND=LAND,LREC=L1)
 ETNORTH(ISLON:IELON,1)=TMP2DIM(ISLON:IELON)
 CALL Nc_READ(FileName1,'EL',TMP2DIM,LAND=LAND,LREC=L2)
 ETNORTH(ISLON:IELON,2)=TMP2DIM(ISLON:IELON)
! Boundary data for average V current
 CALL Nc_READ(FileName,'VA',TMP2DIM,LAND=LAND,LREC=L1) 
 VANORTH(ISLON:IELON,1)=TMP2DIM(ISLON:IELON)
 CALL Nc_READ(FileName1,'VA',TMP2DIM,LAND=LAND,LREC=L2) 
 VANORTH(ISLON:IELON,2)=TMP2DIM(ISLON:IELON)
! 
 DO I=ISLON,IELON
 IF(FSM(I,IELAT)==1)THEN
   DO K=1,JJTIME
   IF(ETNORTH(I,K)>5.)THEN
    WRITE(6,*)I,K,"ET_N=",ETNORTH(I,K)
   STOP
   END IF
   DO J=1,KB
    IF(SNORTH(I,J,K)>45.OR.TNORTH(I,J,K)>45)THEN
     WRITE(6,*)I,J,K,"SAL_N=",SNORTH(I,J,K),"TEMP_N=",TNORTH(I,J,K)
     stop
    END IF
   END DO
   END DO
 ELSE
  SNORTH(I,:,:)=0
  TNORTH(I,:,:)=0
  ETNORTH(I,:)=0
 END IF
 IF(DVM(I,IELAT)==1)THEN
   DO K=1,JJTIME  
    IF(VANORTH(I,K)>5)THEN
    WRITE(6,*) I,K,"VA_N=",VANORTH(I,K)
    STOP
    END IF
   END DO
 ELSE
  VANORTH(I,:)=0
 END IF
  
 END DO

 END IF
!>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
! SET WEST BOUNDARY
 IF(RFW)THEN



 WRITE(6,*)MYID," READ WEST BOUDARY DATA ",L1,L2
 FileName=trim(input)//'bc/'//trim(YYYYX)//'bc_w.nc'
 FileName1=trim(input)//'bc/'//trim(YYYYXX)//'bc_w.nc'
 WRITE(6,*)MYID,TRIM(FileName)
 WRITE(6,*)MYID,TRIM(FileName1)
! Boundary data for salinity
 CALL Nc_READ(FileName,'SALT',TMPJM,LAND=LAND,I1=1,J1=1,LREC=L1) 
 SWEST(ISLAT:IELAT,:,1)=TMPJM(ISLAT:IELAT,:)
 CALL Nc_READ(FileName1,'SALT',TMPJM,LAND=LAND,I1=1,J1=1,LREC=L2) 
 SWEST(ISLAT:IELAT,:,2)=TMPJM(ISLAT:IELAT,:)
! Boundary data for temperature 
 CALL Nc_READ(FileName,'TEMP',TMPJM,LAND=LAND,I1=1,J1=1,LREC=L1) 
 TWEST(ISLAT:IELAT,:,1)=TMPJM(ISLAT:IELAT,:)
 CALL Nc_READ(FileName1,'TEMP',TMPJM,LAND=LAND,I1=1,J1=1,LREC=L2) 
 TWEST(ISLAT:IELAT,:,2)=TMPJM(ISLAT:IELAT,:)
! Boundary data for CURU 
 CALL Nc_READ(FileName,'CURU',TMPJM,LAND=LAND,I1=1,J1=1,LREC=L1) 
 UWEST(ISLAT:IELAT,:,1)=TMPJM(ISLAT:IELAT,:)
 CALL Nc_READ(FileName1,'CURU',TMPJM,LAND=LAND,I1=1,J1=1,LREC=L2) 
 UWEST(ISLAT:IELAT,:,2)=TMPJM(ISLAT:IELAT,:)
! Boundary data for CURV 
 CALL Nc_READ(FileName,'CURV',TMPJM,LAND=LAND,I1=1,J1=1,LREC=L1) 
 VWEST(ISLAT:IELAT,:,1)=TMPJM(ISLAT:IELAT,:)
 CALL Nc_READ(FileName1,'CURV',TMPJM,LAND=LAND,I1=1,J1=1,LREC=L2) 
 VWEST(ISLAT:IELAT,:,2)=TMPJM(ISLAT:IELAT,:)
!Boundary data for SEA LEVEL 
 CALL Nc_READ(FileName,'EL',TMP2DJM,LAND=LAND,LREC=L1) 
 ETWEST(ISLAT:IELAT,1)=TMP2DJM(ISLAT:IELAT)
 CALL Nc_READ(FileName1,'EL',TMP2DJM,LAND=LAND,LREC=L2) 
 ETWEST(ISLAT:IELAT,2)=TMP2DJM(ISLAT:IELAT)
! Boundary data for average V current
 CALL Nc_READ(FileName,'UA',TMP2DJM,LAND=LAND,LREC=L1) 
 UAWEST(ISLAT:IELAT,1)=TMP2DJM(ISLAT:IELAT)
 CALL Nc_READ(FileName1,'UA',TMP2DJM,LAND=LAND,LREC=L2) 
 UAWEST(ISLAT:IELAT,2)=TMP2DJM(ISLAT:IELAT)
! 
 DO I=ISLAT,IELAT
  IF(FSM(ISLON,I)==1)THEN
    DO K=1,JJTIME
     IF(ETWEST(I,K)>5)THEN
     WRITE(6,*) I,K,"ET_W=",ETWEST(I,K)
     STOP
     END IF
     DO J=1,KB
      IF(SWEST(I,J,K)>45.OR.TWEST(I,J,K)>45)THEN
      WRITE(6,*)I,J,K,"SAL_W=",SWEST(I,J,K),"TEMP_W=",TWEST(I,J,K)
      stop
      END IF
     END DO
   END DO
 ELSE
   SWEST(I,:,:)=0
   TWEST(I,:,:)=0
   ETWEST(I,:)=0
 END IF

 IF(DUM(ISLON,I)==1)THEN
  DO K=1,JJTIME
  IF(UAWEST(I,K)>5)THEN
     WRITE(6,*) I,K,"UA_W=",UAWEST(I,K)
  END IF
  END DO
 ELSE
  UAWEST(I,:)=0
 END IF
 
 END DO

 END IF
!>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
! SET EAST BOUNDARY
 IF(RFE)THEN


 WRITE(6,*)MYID," READ EAST BOUDARY DATA ",L1,L2
 FileName=trim(input)//'bc/'//trim(YYYYX)//'bc_e.nc'
 FileName1=trim(input)//'bc/'//trim(YYYYXX)//'bc_e.nc'
 WRITE(6,*)MYID,TRIM(FileName)
 WRITE(6,*)MYID,TRIM(FileName1)
! Boundary data for salinity
 CALL Nc_READ(FileName,'SALT',TMPJM,LAND=LAND,I1=1,J1=1,LREC=L1) 
 SEAST(ISLAT:IELAT,:,1)=TMPJM(ISLAT:IELAT,:)
 CALL Nc_READ(FileName1,'SALT',TMPJM,LAND=LAND,I1=1,J1=1,LREC=L2) 
 SEAST(ISLAT:IELAT,:,2)=TMPJM(ISLAT:IELAT,:)
! Boundary data for temperature 
 CALL Nc_READ(FileName,'TEMP',TMPJM,LAND=LAND,I1=1,J1=1,LREC=L1) 
 TEAST(ISLAT:IELAT,:,1)=TMPJM(ISLAT:IELAT,:)
 CALL Nc_READ(FileName1,'TEMP',TMPJM,LAND=LAND,I1=1,J1=1,LREC=L2) 
 TEAST(ISLAT:IELAT,:,2)=TMPJM(ISLAT:IELAT,:)
! Boundary data for CURU 
 CALL Nc_READ(FileName,'CURU',TMPJM,LAND=LAND,I1=1,J1=1,LREC=L1) 
 UEAST(ISLAT:IELAT,:,1)=TMPJM(ISLAT:IELAT,:)
 CALL Nc_READ(FileName1,'CURU',TMPJM,LAND=LAND,I1=1,J1=1,LREC=L2) 
 UEAST(ISLAT:IELAT,:,2)=TMPJM(ISLAT:IELAT,:)
! Boundary data for CURU 
 CALL Nc_READ(FileName,'CURV',TMPJM,LAND=LAND,I1=1,J1=1,LREC=L1) 
 VEAST(ISLAT:IELAT,:,1)=TMPJM(ISLAT:IELAT,:)
 CALL Nc_READ(FileName1,'CURV',TMPJM,LAND=LAND,I1=1,J1=1,LREC=L2) 
 VEAST(ISLAT:IELAT,:,2)=TMPJM(ISLAT:IELAT,:)
!Boundary data for SEA LEVEL 
 CALL Nc_READ(FileName,'EL',TMP2DJM,LAND=LAND,LREC=L1) 
 ETEAST(ISLAT:IELAT,1)=TMP2DJM(ISLAT:IELAT)
 CALL Nc_READ(FileName1,'EL',TMP2DJM,LAND=LAND,LREC=L2) 
 ETEAST(ISLAT:IELAT,2)=TMP2DJM(ISLAT:IELAT)
! Boundary data for average V current
 CALL Nc_READ(FileName,'UA',TMP2DJM,LAND=LAND,LREC=L1) 
 UAEAST(ISLAT:IELAT,1)=TMP2DJM(ISLAT:IELAT)
 CALL Nc_READ(FileName1,'UA',TMP2DJM,LAND=LAND,LREC=L2) 
 UAEAST(ISLAT:IELAT,2)=TMP2DJM(ISLAT:IELAT)
! 
 DO I=ISLAT,IELAT
 IF(FSM(IELON,I)==1)THEN
   DO K=1,JJTIME
   IF(ETEAST(I,K)>5.)THEN
   WRITE(6,*) I,K,"ET_E=",ETEAST(I,K)
   STOP
   END IF
   DO J=1,KB
    IF(SEAST(I,J,K)>45.OR.TEAST(I,J,K)>45)THEN
     WRITE(6,*) I,J,K,"SAL_E=",SEAST(I,J,K),"TEMP_E=",TEAST(I,J,K)
     stop
    END IF
   END DO
   END DO
 ELSE
  SEAST(I,:,:)=0
  TEAST(I,:,:)=0
  ETEAST(I,:)=0
 END IF

 IF(DUM(IELON,I)==1)THEN
  DO K=1,JJTIME
   IF(UAEAST(I,K)>5)THEN
   WRITE(6,*) I,K,"UA_E=",UAEAST(I,K)
   STOP
   END IF
  END DO
 ELSE
  UAEAST(I,:)=0
 END IF

 END DO

 END IF
!>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 RETURN
 END
