 SUBROUTINE SET_CBC
 USE DATA_KIND_MOD
 USE ALL_VAR, ONLY : X,Y,H,ZZ,CBC,FSM
 USE CONTROL
 USE CONST
 USE LIMS
 USE PARALLEL_MOD
 IMPLICIT NONE
 REAL(kind_r4),PARAMETER :: Z0B=.01
 REAL(kind_r4),PARAMETER :: CBCMIN=.0025E0 
 REAL(kind_r4),PARAMETER :: CBCMAX=1.00
! A VERY EMPIRICAL SPECIFICATION OF THE BOTTOM ROUGHNESS
!          PARAMETER FOLLOWS
 DO J=ISLAT,IELAT
 DO I=ISLON,IELON
 CBC(I,J)=MAX(CBCMIN,(KAPPA/LOG((1.+ZZ(KBM1))*H(I,J)/Z0B))**2)
 CBC(I,J)=MIN(CBCMAX,CBC(I,J))
! IF(Y(J).GT.20..AND.H(I,J).LT.2800)CBC(I,J)=0.0016*FSM(I,J)
! IF(Y(J).GT.25.25.AND.Y(J).GT.(25.25+(X(I)-120.75)*14.75/3.5))     &
! CBC(I,J)=0.001*FSM(I,J)
! IF(Y(J).GT.33..AND.Y(J).LT.36..AND.X(I).GT.128..AND.X(I).LT.131.) &
! CBC(I,J)=0.0035*FSM(I,J)
 END DO
 END DO
 CALL COMM_2D(CBC,3,3)
 RETURN
 END
