!==============================================================================|
   SUBROUTINE DOMDEC_WAVE           
   USE parallel_mod_wave, only: gather_int,bcast_int,barrier,par_end
   USE CONTROL_WAVE
   USE LIMS_WAVE
   USE NcFileMod
   USE ALL_VAR_WAVE, only : NSP,RFE,RFW,RFN,RFS                             !zhaobiao, c-coupler2
   
!# if defined (MULTIPROCESSOR)

!==============================================================================|
   IMPLICIT NONE
   include "mpif.h"
   INTEGER,PARAMETER :: COE = 5
   INTEGER,DIMENSION(NUMXCPU+1) :: ILAT
   INTEGER,DIMENSION(NUMYCPU+1,NUMXCPU) :: ILON 
   INTEGER,DIMENSION(IM,JM) :: MNSP
   INTEGER I,J,K,KK,MINGRID,LLEFT,LRIGHT
   INTEGER,DIMENSION(6,NPROCS) :: PARTINFO
   INTEGER,DIMENSION(4,NPROCS) :: CORNER 
   INTEGER IJCORNER(4),IJCORNER_LON(4),IJCORNER_LAT(4),IJPART(6)
!   INTEGER,DIMENSION(4) :: NEIGHBOR_LON,NEIGHBOR_LAT
   INTEGER,DIMENSION(4,NPROCS) :: CORNER_LON,CORNER_LAT
   REAL,DIMENSION(IM,JM) :: TMP
   
   CHARACTER*200 FileName
!==============================================================================|

!
!----------------READ IN NODE LIST FROM ***_grd.dat FILE-----------------------!


! READ TOPO FILE DATA
!
  FileName=trim(input)//trim(ModelName)//'_topo.nc'
  WRITE(6,*) "TOPO data file is   ", TRIM(FileName)
  CALL Nc_Read(FileName,'nsp',TMP,LAND=0.)
  MNSP=INT(TMP)
!
!-------------DECOMPOSE ELEMENTS USING METIS GRAPH PARTITIONING ---------------!
!
  CALL PARTITION(MNSP,NUMXCPU,NUMYCPU,IM,JM,ILAT,ILON,COE)
!  END IF

!---------------------BROADCAST RESULT TO ALL PROCESSORS-----------------------!
!  CALL MPI_BCAST(EL_PID,NGL,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
  
  I = MYID/NUMYCPU+1
  J = MOD(MYID,NUMYCPU)+1
  
  ISLON=ILAT(I)+1
  IF(I==1)ISLON=ILAT(I)
  IELON=ILAT(I+1)
  ISLAT=ILON(J,I)+1
  IELAT=ILON(J+1,I)

  I=SUM(SUM(MNSP(ISLON:IELON,ISLAT:IELAT),DIM=1))
  J=(IELON-ISLON+1)*(IELAT-ISLAT+1)
  I=I+(J-I)/COE

  PARTINFO(1,MYID+1) = MYID
  PARTINFO(2,MYID+1) = ISLON
  PARTINFO(3,MYID+1) = IELON
  PARTINFO(4,MYID+1) = ISLAT
  PARTINFO(5,MYID+1) = IElAT
  PARTINFO(6,MYID+1) = I 

  IJPART=PARTINFO(:,MYID+1)
 ! CALL GATHER_INT(PARTINFO(:,MYID+1))
  CALL GATHER_INT(IJPART,PARTINFO(:,MYID+1))
  CALL BCAST_INT(PARTINFO)

!>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
! SET THE HALO LOCATION
  I = MYID/NUMYCPU+1
  J = MOD(MYID,NUMYCPU)+1
!  ILEFT=MPI_PROC_NULL
!  IRIGHT=MPI_PROC_NULL
  IUP=MYID+1
  IDOWN=MYID-1
  IF(J==1)IDOWN= MPI_PROC_NULL 
  IF(J==NUMYCPU)IUP= MPI_PROC_NULL 


  LLEFT=I-1
  LRIGHT=I+1

  IF(I==1)LLEFT=NUMXCPU
  IF(I==NUMXCPU)LRIGHT=1

  ALLOCATE(LHALO(ISLAT:IELAT),RHALO(ISLAT:IELAT))
  LHALO=MPI_PROC_NULL
  RHALO=MPI_PROC_NULL

  DO K = ISLAT,IELAT

  DO KK=(LLEFT-1)*NUMYCPU+1,LLEFT*NUMYCPU
  IF(K>=PARTINFO(4,KK).AND.K<=PARTINFO(5,KK))THEN
  LHALO(K)=PARTINFO(1,KK)
  EXIT
  END IF
  END DO


  DO KK=(LRIGHT-1)*NUMYCPU+1,LRIGHT*NUMYCPU
  IF(K>=PARTINFO(4,KK).AND.K<=PARTINFO(5,KK))THEN
  RHALO(K)=PARTINFO(1,KK)
  EXIT
  END IF
  END DO

  END DO

  DO K = ISLAT,IELAT
  IF(LHALO(K)==MPI_PROC_NULL.OR.RHALO(K)==MPI_PROC_NULL)THEN
  WRITE(6,*) MYID,"ERROR HALO",LHALO(K),RHALO(K)
  CALL PAR_END
  END IF
  END DO
!>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  CALL BARRIER 
  DO I=1,NPROCS
     WRITE(6,*) PARTINFO(:,I)
  END DO
!>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  NEIGHBOR=MPI_PROC_NULL
  
  K = ISLAT-1
  IF(K/=0)THEN 
  DO KK=(LLEFT-1)*NUMYCPU+1,LLEFT*NUMYCPU
  IF(K>=PARTINFO(4,KK).AND.K<=PARTINFO(5,KK))THEN
  NEIGHBOR(1)=PARTINFO(1,KK)
  NEIGHBOR_LON(1)=ISLON-1
  IF(ISLON==1)NEIGHBOR_LON(1)=IM-1
  NEIGHBOR_LAT(1)=ISLAT-1
  CORNER_REC(1,1)=ISLON-1
  CORNER_REC(2,1)=ISLAT-1
  EXIT
  END IF
  END DO

  DO KK=(LRIGHT-1)*NUMYCPU+1,LRIGHT*NUMYCPU
  IF(K>=PARTINFO(4,KK).AND.K<=PARTINFO(5,KK))THEN
  NEIGHBOR(2)=PARTINFO(1,KK)
  NEIGHBOR_LON(2)=IELON+1
  IF(IELON==IM)NEIGHBOR_LON(2)=2
  NEIGHBOR_LAT(2)=ISLAT-1
  CORNER_REC(1,2)=IELON+1
  CORNER_REC(2,2)=ISLAT-1
  EXIT
  END IF
  END DO
  END IF
!===============================================
! add by wgs 20140215 17:42:52 
! add these just for novalid boundary check
  IF(K==0)THEN
  CORNER_REC(1,1)=ISLON-1
  CORNER_REC(2,1)=ISLAT-1
  CORNER_REC(1,2)=IELON+1
  CORNER_REC(2,2)=ISLAT-1
  END IF  
!===============================================

  K = IELAT+1

  IF(K/=JM+1)THEN
  DO KK=(LLEFT-1)*NUMYCPU+1,LLEFT*NUMYCPU
  IF(K>=PARTINFO(4,KK).AND.K<=PARTINFO(5,KK))THEN
  NEIGHBOR(4)=PARTINFO(1,KK)
  NEIGHBOR_LON(4)=ISLON-1
  IF(ISLON==1)NEIGHBOR_LON(4)=IM-1
  NEIGHBOR_LAT(4)=IELAT+1
  CORNER_REC(1,4)=ISLON-1
  CORNER_REC(2,4)=IELAT+1
  EXIT
  END IF
  END DO

  DO KK=(LRIGHT-1)*NUMYCPU+1,LRIGHT*NUMYCPU
  IF(K>=PARTINFO(4,KK).AND.K<=PARTINFO(5,KK))THEN
  NEIGHBOR(3)=PARTINFO(1,KK)
  NEIGHBOR_LON(3)=IELON+1
  IF(IELON==IM)NEIGHBOR_LON(3)=2
  NEIGHBOR_LAT(3)=IELAT+1
  CORNER_REC(1,3)=IELON+1
  CORNER_REC(2,3)=IELAT+1
  EXIT
  END IF
  END DO
  END IF
!===============================================
! add by wgs 20140215 17:42:52 
! add these just for novalid boundary check
  IF(K==JM+1)THEN
  CORNER_REC(1,4)=ISLON-1
  CORNER_REC(2,4)=IELAT+1
  CORNER_REC(1,3)=IELON+1
  CORNER_REC(2,3)=IELAT+1
  END IF  
!===============================================

  CORNER(:,MYID+1)=NEIGHBOR
  CORNER_LON(:,MYID+1)=NEIGHBOR_LON
  CORNER_LAT(:,MYID+1)=NEIGHBOR_LAT

  IJCORNER=CORNER(:,MYID+1)
  IJCORNER_LON=CORNER_LON(:,MYID+1)
  IJCORNER_LAT=CORNER_LAT(:,MYID+1)
  CALL GATHER_INT(IJCORNER,CORNER(:,MYID+1))
  CALL GATHER_INT(IJCORNER_LON,CORNER_LON(:,MYID+1))
  CALL GATHER_INT(IJCORNER_LAT,CORNER_LAT(:,MYID+1))
  CALL BCAST_INT(CORNER)
  CALL BCAST_INT(CORNER_LON)
  CALL BCAST_INT(CORNER_LAT)
!  WRITE(6,*) MYID,"RECEIVE ID",NEIGHBOR

  KK=0
  DO K=1,NPROCS
  DO I=1,4
  IF(CORNER(I,K)==MYID)KK=KK+1
  END DO
  END DO

  IF(KK>=1)THEN
  NUM_CORNER_SEND=KK
  ALLOCATE(CORNER_SEND(3,KK))
  ELSE
  NUM_CORNER_SEND=MPI_PROC_NULL
  RETURN
  END IF

  KK=0
  DO K=1,NPROCS
  DO I=1,4
  IF(CORNER(I,K)==MYID)THEN
  KK=KK+1
  CORNER_SEND(1,KK)=CORNER_LON(I,K)
  CORNER_SEND(2,KK)=CORNER_LAT(I,K)
  CORNER_SEND(3,KK)=K-1
  END IF
  END DO
  END DO

!! BDY FLG
  RFE=0;RFW=0;RFN=0;RFS=0 
  IF(ISLON==1)RFW=1
  IF(IELON==IM)RFE=1
  IF(IELAT==JM)RFN=1
  IF(ISLAT==1)RFS=1

  IF(KK/=NUM_CORNER_SEND)THEN
  WRITE(6,*) "ERROR SEND ID",MYID,KK,NUM_CORNER_SEND
  CALL PAR_END
  END IF
!  CALL BARRIER

!>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  RETURN
  END SUBROUTINE DOMDEC_WAVE
!==============================================================================|
