 SUBROUTINE INTER(U1,U2,V1,V2,AA,BB,CC,DD,XT,YT,VALUE)
 use data_kind_mod_wave
 IMPLICIT NONE
 REAL(kind_r4),INTENT(IN) :: U1,U2,V1,V2,AA,BB,CC,DD,XT,YT
 REAL(kind_r4),INTENT(OUT) :: VALUE

 REAL(kind_r4) :: DOX,DOY,YVALUE,R,Q,PHIA,PHIC,PHIB,PHID
!
 DOX=U2-U1
 DOY=V2-V1
!
 IF(DOX==0.0.AND.DOY==0.0)THEN
 YVALUE=(AA+BB+CC+DD)/4.0
 VALUE=YVALUE
 RETURN
 ENDIF
!
 IF(DOX==0.0.AND.DOY/=0.0)THEN
 R=(YT-V1)/DOY
 YVALUE=R*(CC+DD)/2.0+(1-R)*(AA+BB)/2.0
 VALUE=YVALUE
 RETURN
 ENDIF
!
 IF(DOX/=0.0.AND.DOY==0.0)THEN
 Q=(XT-U1)/DOX
 YVALUE=Q*(BB+DD)/2.0+(1-Q)*(AA+CC)/2.0
 VALUE=YVALUE
 RETURN
 ENDIF
!
 IF(DOX/=0.0.AND.DOY/=0.0)THEN
 Q=(XT-U1)/DOX
 R=(YT-V1)/DOY
 PHIA=(1-Q)*(1-R)
 PHIB=Q*(1-R)
 PHIC=(1-Q)*R
 PHID=Q*R
!
 YVALUE=AA*PHIA
 YVALUE=YVALUE+BB*PHIB
 YVALUE=YVALUE+CC*PHIC
 YVALUE=YVALUE+DD*PHID
 VALUE=YVALUE
 RETURN
 ENDIF  
!
 END 
