 SUBROUTINE MEAN2(AE,ASI,AWF,AWK,ARK)
 USE data_kind_mod_wave
 USE CONTROL_WAVE, ONLY : ISLAT,IELAT,ISLON,IELON 
 USE CONST_WAVE, ONLY : KLD,KL,JL,ZPI,ZERO
 USE ALL_VAR_WAVE, ONLY : NSP,DWK,WF,WK,E,WKH
 IMPLICIT NONE
 REAL(kind_r4),DIMENSION(ISLON:IELON,ISLAT:IELAT),INTENT(OUT) :: AE,ASI,AWF,AWK,ARK
! >>>>>>>>>>>>>>>>>>>>>>>>>>
 INTEGER IA,IC,K,K1,I,I1,J
 REAL(kind_r4) DWKK,WFK,WFK1,WSK,WSK1,WKK,WKK1,EKJ,EKJ1
!
 AE=ZERO;ASI=ZERO;AWF=ZERO;AWK=ZERO;ARK=ZERO

 DO IC=ISLAT,IELAT
 DO IA=ISLON,IELON
!
 IF(NSP(IA,IC)/=1)CYCLE
!
 DO K=1,KLD
 K1=K+1
 I=K-KL+1
 I1=I+1
 DWKK=DWK(K)
 WFK=WF(K,IA,IC)
 WFK1=WF(K1,IA,IC)
!WFK=FR(K)
!WFK1=FR(K1)
 WSK=ZPI*WFK
 WSK1=ZPI*WFK1
 WKK=WK(K)
 WKK1=WK(K1)

 DO J=1,JL
 IF (K.LT.KL) THEN
    EKJ=E(K,J,IA,IC)
    EKJ1=E(K1,J,IA,IC)
 ELSE
    EKJ=E(KL,J,IA,IC)*WKH(I)
    EKJ1=E(KL,J,IA,IC)*WKH(I1)
 ENDIF
 AE(IA,IC)=AE(IA,IC)+(EKJ+EKJ1)*DWKK
 AWF(IA,IC)=AWF(IA,IC)+(EKJ*WFK+EKJ1*WFK1)*DWKK
 ASI(IA,IC)=ASI(IA,IC)+(EKJ/WSK+EKJ1/WSK1)*DWKK
 AWK(IA,IC)=AWK(IA,IC)+(EKJ*WKK+EKJ1*WKK1)*DWKK
 ARK(IA,IC)=ARK(IA,IC)+(EKJ/SQRT(WKK)+EKJ1/SQRT(WKK1))*DWKK

 END DO
 END DO
!
 ASI(IA,IC)=AE(IA,IC)/ASI(IA,IC)
 AWF(IA,IC)=AWF(IA,IC)/AE(IA,IC)
 AWK(IA,IC)=AWK(IA,IC)/AE(IA,IC)
 ARK(IA,IC)=(AE(IA,IC)/ARK(IA,IC))**2
 END DO
 END DO
 RETURN
 END
