 SUBROUTINE PROPAGAT
 USE data_kind_mod_wave
 USE CONTROL_WAVE, ONLY : ISLAT,IELAT,ISLON,IELON,DX,DY,DELTTM
 USE CONST_WAVE, ONLY : ZPI,RS,JL,KL,PI,G,WKMIN,KLD,DELTTH,JLP1
 USE LIMS_WAVE, ONLY : IM,GRID
 USE ALL_VAR_WAVE, ONLY : XGRID,YGRID,NSP,D,UXX,UXY,UYX,UYY,THET,WF,CCG,WK,& 
               UX,UY,RS2DLAT,WKH,THET,E,EE
 IMPLICIT NONE
 REAL(kind_r4) :: X0,Y0,D0,DDDX0,DDDY0,DUXDX0,DUXDY0,DUYDX0,DUYDY0 
 REAL(kind_r4) :: TH0,SINTH,COSTH,DELTT,WK0,WS0,DK0,CG,CGX,CGY,WECS,WKS
 REAL(kind_r4) :: DELTS,X_D,Y_D,RADX_D,RADY_D,XX,YY,X1,X2,Y1,Y2,DSIDD,ANGX_D,ANGY_D
 REAL(kind_r4) :: SSR1,SSR2,SSRWK,SSRTH,FIEN,FIEN1,WK1,WK2,DTTH0,THS
 REAL(kind_r4) :: TH1,TH2,E11,E12,E13,E14,E1,E41,E42,E43,E44,E4
 REAL(kind_r4) :: E21,E22,E23,E24,E2,E31,E32,E33,E34,E3,EXXYY
 INTEGER(kind_in) :: IXX,IXX1,JYY,JYY1,IWK,IWK1,IYYZ,I,I1,JTH,JTH1
 INTEGER(kind_in) IA,IC,K,J,IJLONLAT

 DO IA=ISLON,IELON
 DO IC=ISLAT,IELAT
!
 IF(NSP(IA,IC)/=1)CYCLE
!
 !!X0=X(IA)
 !!Y0=Y(IC)
 X0=XGRID(IA,IC)
 Y0=YGRID(IA,IC)
 D0=D(IA,IC)
!
 !!DDDX0=(D(IA+1,IC)-D(IA-1,IC))/(2*DX)
 !!DDDY0=(D(IA,IC+1)-D(IA,IC-1))/(2*DY)
 DDDX0=(D(IA+1,IC)-D(IA-1,IC))/(DX(IA+1,IC)+DX(IA,IC))
 DDDY0=(D(IA,IC+1)-D(IA,IC-1))/(DY(IA,IC+1)+DY(IA,IC))
 !!DDDX0=0.5*(D(IA+1,IC)-D(IA-1,IC))/(DX(IA+1,IC)+2*DX(IA,IC)+DX(IA-1,IC))
 !!DDDY0=0.5*(D(IA,IC+1)-D(IA,IC-1))/(DY(IA,IC+1)+2*DY(IA,IC)+DY(IA,IC-1))
! 
 DUXDX0=UXX(IA,IC)
 DUXDY0=UXY(IA,IC)
 DUYDX0=UYX(IA,IC)
 DUYDY0=UYY(IA,IC)
!
 DO J=1,JL
    TH0=THET(J)
    SINTH=SIN(TH0)
    COSTH=COS(TH0)
    DO K=1,KL
       DELTT=DELTTM*60.
       WK0=WK(K)
       WS0=ZPI*WF(K,IA,IC)
       DK0=D0*WK0
       CG=CCG(K,IA,IC)
       CGX=CG*COSTH
       CGY=CG*SINTH
!! 1.  "THE CALCULATION OF WAVE ENGERY-CURRENT SPREADING"
       WECS=SQRT((CGX+UX(IA,IC))**2+(CGY+UY(IA,IC))**2)
       DELTS=WECS*DELTT
       X_D=DELTS*COSTH
       Y_D=DELTS*SINTH
       RADX_D=X_D/RS2DLAT(IA,IC)
       RADY_D=Y_D/RS
       ANGX_D=RADX_D*180.0/PI
       ANGY_D=RADY_D*180.0/PI
       !!IF(ABS(ANGX_D)>DX.OR.ABS(ANGY_D)>DY) THEN
       IF(ABS(ANGX_D)>DX(IA,IC).OR.ABS(ANGY_D)>DY(IA,IC)) THEN
!         WRITE(6,*) IA,IC,ANGX_D,ANGY_D,D0,J,K
         WRITE(6,*)  'BE CAREFUL ! PROGRAM HAVE TO STOP ! IN LINE 52 PROPGATE CODE!'
         WRITE(6,*)  'NEED TO REDUCE TIME STEP'
         STOP
       END IF
!!
       XX=X0-DELTT*(CGX+UX(IA,IC))/RS2DLAT(IA,IC)*180./PI
       YY=Y0-DELTT*(CGY+UY(IA,IC))/RS*180./PI
       !!IXX=INT((XX-X(1))/DX)+1
       !!JYY=INT((YY-Y(1))/DY)+1
       IXX=-1;JYY=-1
       DO IJLONLAT=IA-1,IA+1
          !!IF(XX>=X(IJLONLAT).and.XX<X(IJLONLAT+1))THEN
          IF(XX>=XGRID(IJLONLAT,IC).and.XX<XGRID(IJLONLAT+1,IC))THEN
          IXX=IJLONLAT
          exit
          END IF
       END DO
       DO IJLONLAT=IC-1,IC+1
          !!IF(YY>=Y(IJLONLAT).and.YY<Y(IJLONLAT+1))THEN
          IF(YY>=YGRID(IA,IJLONLAT).and.YY<YGRID(IA,IJLONLAT+1))THEN
          JYY=IJLONLAT
          exit
          END IF
       END DO

      IF(IXX==-1.or.JYY==-1)THEN
       WRITE(6,*),IA,IC,"WGS",IXX,JYY
       STOP
      END IF

       IF(XX<XGRID(1,IC).AND.XX>=XGRID(0,IC))IXX=0
       IF(XX<XGRID(IM+1,IC).AND.XX>=XGRID(IM,IC))IXX=IM
       IF(IXX<0.OR.JYY<1)THEN
         WRITE(6,*) "ERR PROPGATE",IXX,XX,JYY,YY
       STOP
       END IF
!
       IXX1=IXX+1
       JYY1=JYY+1
!
       !!X1=X(IXX)
       !!X2=X(IXX1)
       !!Y1=Y(JYY)
       !!Y2=Y(JYY1)
       X1=XGRID(IXX,IC)
       X2=XGRID(IXX1,IC)
       Y1=YGRID(IA,JYY)
       Y2=YGRID(IA,JYY1)
!
!******  2.  "THE EFFECT OF REFRACTION CAUSED BY TOPOGRAPHY AND CURRENT"
!
      IF (DK0<40.) THEN
         DSIDD=0.5*G/COSH(DK0)*WK0**2/WS0/COSH(DK0)
      ELSE
         DSIDD=0.
      ENDIF
!
      SSR1=(DSIDD*DDDX0+WK0*COSTH*DUXDX0+WK0*SINTH*DUYDX0)
      SSR2=(DSIDD*DDDY0+WK0*COSTH*DUXDY0+WK0*SINTH*DUYDY0)
      SSRWK=-(SSR1*COSTH/RS2DLAT(IA,IC)+SSR2*SINTH/RS)
      SSRTH=(SSR1*SINTH/RS2DLAT(IA,IC)-SSR2*COSTH/RS)/WK0
      SSRTH=SSRTH-CG*COSTH*TAND(YGRID(IA,IC))/RS
!      SSRTH=SSRTH-CG*COSTH*TAND(90.-(IC-1)*GRID)/RS
      WKS=WK0-DELTT*SSRWK
      IF(WKS<0.)WKS=0.
      IF(WKS<=WKMIN)THEN
        IWK=1
        IWK1=1
        FIEN=0.
        FIEN1=1.
        WK1=0.
        WK2=WK(IWK1)
      ELSE
        IF(WKS<WK(KLD))THEN
!
!======= THE FOLLOWING BELONGS TO THE LAGFD-WAM WAVE MODEL
!	IWK=INT(LOG(WKS/WKMIN)/LOG(PWK))+1
!==========================================================
!	IF (WKS.LT.WK(IWK)) IWK=IWK-1
!	IF (WKS.GT.WK(IWK+1)) IWK=IWK+1
!====   THE FOLLOWING IS MODIFIED BY YANG YONGZENG ===============!
!
        DO IYYZ=1,KLD
        IF(WKS>=WK(IYYZ).AND.WKS<WK(IYYZ+1))IWK=IYYZ
        ENDDO
        IWK1=IWK+1
!=====================================================================!
        WK1=WK(IWK)
        WK2=WK(IWK1)
        IF(IWK<KL)THEN
          IWK1=IWK+1
          FIEN=1.
          FIEN1=1.
        ELSE
          I=IWK-KL+1
          I1=I+1
          FIEN=WKH(I)
          FIEN1=WKH(I1)
          IWK=KL
          IWK1=KL
        ENDIF
        ELSE
          WKS=WK(KLD)
          IWK=KL
          IWK1=KL
          I=KLD-KL+1
          I1=I+1
          FIEN=WKH(I)
          FIEN1=WKH(I1)
        ENDIF
      ENDIF
!
     DTTH0=DELTT*SSRTH
     THS=TH0-DTTH0
     IF(THS<(-1.0)*ZPI.OR.THS>=(2.0)*ZPI)THEN
!       THS=TH0
        WRITE(6,*)  IA,IC,K,J
        WRITE(6,*)  THS,TH0,ZPI
        WRITE(6,*)  SSRTH,TAND(YGRID(IA,IC)),YGRID(IA,IC),NSP(IA,IC),D(IA,IC) 
        WRITE(6,*)  'THE WAVE IS SPINNING ,I CAN NOT COMPUTER IT !!!'
       STOP
     ENDIF
     IF(THS>=ZPI)THS=THS-ZPI
     IF(THS<0.)THS=THS+ZPI
     JTH=INT(THS/DELTTH)+1
     JTH1=JTH+1
     IF(JTH==JLP1)THEN
       JTH=JL
       JTH1=1
     ENDIF
     IF(JTH1==JLP1)JTH1=1
!
     TH1=THET(JTH)
     TH2=THET(JTH+1)
!
!* 3.  "DETERMING THE WAVE ENERGY AT THE PHYSICAL SPACE POINT (XX,YY)
!*	AND THE WAVE SPACE POINT (WKS,THS)"
!* 3.1 "AT PHYSICAL SPACE POINT (X1,Y1)"
!
     E11=EE(IWK ,JTH ,IXX,JYY)*FIEN
     E12=EE(IWK1,JTH ,IXX,JYY)*FIEN1
     E13=EE(IWK ,JTH1,IXX,JYY)*FIEN
     E14=EE(IWK1,JTH1,IXX,JYY)*FIEN1
     CALL INTER(WK1,WK2,TH1,TH2,E11,E12,E13,E14,WKS,THS,E1)
!
!* 3.2 "AT PHYSICAL SPACE POINT (X2,Y1)"
!
     E21=EE(IWK ,JTH ,IXX1,JYY)*FIEN
     E22=EE(IWK1,JTH ,IXX1,JYY)*FIEN1
     E23=EE(IWK ,JTH1,IXX1,JYY)*FIEN
     E24=EE(IWK1,JTH1,IXX1,JYY)*FIEN1
     CALL INTER(WK1,WK2,TH1,TH2,E21,E22,E23,E24,WKS,THS,E2)
!
!* 3.3 "AT PHYSICAL SPACE POINT (X1,Y2)"
!
     E31=EE(IWK ,JTH ,IXX,JYY1)*FIEN
     E32=EE(IWK1,JTH ,IXX,JYY1)*FIEN1
     E33=EE(IWK ,JTH1,IXX,JYY1)*FIEN
     E34=EE(IWK1,JTH1,IXX,JYY1)*FIEN1
     CALL INTER(WK1,WK2,TH1,TH2,E31,E32,E33,E34,WKS,THS,E3)
!
!* 3.4 "AT PHYSICAL SPACE POINT (X2,Y2)"
!
     E41=EE(IWK ,JTH ,IXX1,JYY1)*FIEN
     E42=EE(IWK1,JTH ,IXX1,JYY1)*FIEN1
     E43=EE(IWK ,JTH1,IXX1,JYY1)*FIEN
     E44=EE(IWK1,JTH1,IXX1,JYY1)*FIEN1
!
     CALL INTER(WK1,WK2,TH1,TH2,E41,E42,E43,E44,WKS,THS,E4)
!
!* 3.5 "AT PHYSICAL SPACE POINT (XX,YY)"
!
     CALL INTER(X1,X2,Y1,Y2,E1,E2,E3,E4,XX,YY,EXXYY)
!
     E(K,J,IA,IC)=EXXYY
!    WRITE(6,*)  E(K,J,IA,IC)
     END DO ! >> 500
   END DO  !>>200

 END DO
 END DO
!
 RETURN
 END
